<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_jcf-select-opener_1</name>
   <tag></tag>
   <elementGuidId>e3fbcea8-5db5-4add-851a-456236be3b19</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jcf-select-opener</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;5b2ff072-d490-4a8b-a5ee-a82a17e9c5ff&quot;)/div[@class=&quot;form-content-column&quot;]/div[@class=&quot;form-group valid&quot;]/div[@class=&quot;form-elements&quot;]/span[@class=&quot;jcf-select jcf-unselectable jcf-select-form-control jcf-focus jcf-drop-active jcf-drop-flipped jcf-pressed&quot;]/span[@class=&quot;jcf-select-opener&quot;]</value>
   </webElementProperties>
</WebElementEntity>
