<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Nurse</name>
   <tag></tag>
   <elementGuidId>53d7f382-d9db-40a2-b2d0-e7053f589ede</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//span[(text() = 'Nurse' or . = 'Nurse')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jcf-option jcf-hover</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>4</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nurse</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;home home-page acorda-cvt page page-cfabb956-6eb3-4020-bde0-76e089d8c098&quot;]/div[@class=&quot;jcf-select-drop jcf-select-form-control jcf-select-jcf-hidden jcf-unselectable jcf-drop-flipped&quot;]/div[@class=&quot;jcf-select-drop-content&quot;]/span[@class=&quot;jcf-list&quot;]/span[@class=&quot;jcf-list-content&quot;]/ul[1]/li[5]/span[@class=&quot;jcf-option jcf-hover&quot;]</value>
   </webElementProperties>
</WebElementEntity>
