<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Yes</name>
   <tag></tag>
   <elementGuidId>1011ef08-b9ad-4e81-9d06-45d0650f7ec9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html[1]/body[@class=&quot;patient patient-home insupport-sublocade modal-open&quot;]/div[@class=&quot;modal modal-disclaimer active&quot;]/div[@class=&quot;modal-contents&quot;]/div[@class=&quot;modal-footer&quot;]/a[@class=&quot;btn btn-secondary large primary-exit&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://insupport-hub-admin.klick.com/specialty-product/patient/find-treatment?zipcode=10010</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-secondary large primary-exit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yes</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;patient patient-home insupport-sublocade modal-open&quot;]/div[@class=&quot;modal modal-disclaimer active&quot;]/div[@class=&quot;modal-contents&quot;]/div[@class=&quot;modal-footer&quot;]/a[@class=&quot;btn btn-secondary large primary-exit&quot;]</value>
   </webElementProperties>
</WebElementEntity>
