<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_InvalidCodeMsg</name>
   <tag></tag>
   <elementGuidId>305aa590-af9f-49e6-89d0-58fce412ce14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.form-error</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
