<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_ZipcodeNotFoundErrorMessage</name>
   <tag></tag>
   <elementGuidId>76877064-6c91-4131-a3e5-83c929eb6dff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.form-error</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
